API to unlock account for a user
Brainberg-in/cc-auth-service pull request #19
Opened 2024-10-25 03:55 UTC by abhishekTraitFit

https://app.clickup.com/t/86cwr6w8d

2024-10-25 04:25 UTC, BhargavaNarendra97 requested changes

2024-10-25 04:25 UTC, BhargavaNarendra97 commented on src/main/java/com/mpsp/cc_auth_service/error/ErrorResponse.java
> +  private String remainingAttempts;
int would be a more suitable type

2024-10-25 04:25 UTC, BhargavaNarendra97 commented on src/main/java/com/mpsp/cc_auth_service/repository/PasswordHistoryRepo.java
> +  @Modifying
looks like resetFailedLognAttempts is a special case of  incrementFailedLoginAttemptsInDb. instead of 2 queries, use the incrementFailedLoginAttemptsInDb and remove resetFailedLognAttempts. Also change the name 'incrementFailedLoginAttemptsInDb'. Probably 'updateFailedLoginAttempts' would be a better and generlaized name

2024-10-25 04:25 UTC, BhargavaNarendra97 commented on src/main/java/com/mpsp/cc_auth_service/service/impl/AuthServiceImpl.java
> +  private static final int PASSWORD_ATTEMPTS = 5;
move this to application.properties

2024-10-25 04:25 UTC, BhargavaNarendra97 commented on src/main/java/com/mpsp/cc_auth_service/service/impl/AuthServiceImpl.java
> +      log.error("Failed to increment login attempts: " + e.getMessage(), e);
e.getMessage() is not required. logger will automatically show it in stack trace

2024-10-25 04:25 UTC, BhargavaNarendra97 commented on src/main/java/com/mpsp/cc_auth_service/service/impl/AuthServiceImpl.java
> +    } catch (Exception e) {
It looks like the only InvalidPasswordException is thrown from try block and you are catching and throwing the same exception. catch block looks redundant to me

2024-10-25 04:25 UTC, BhargavaNarendra97 commented on src/main/java/com/mpsp/cc_auth_service/service/impl/AuthServiceImpl.java
> +  @Transactional(noRollbackFor = InvalidPasswordException.class)
instead of noRollbackFor use propagation=REQUIRES_NEW which makes this to be executed when it's parent method throws an error

2024-10-25 04:25 UTC, BhargavaNarendra97 commented on src/main/java/com/mpsp/cc_auth_service/service/impl/AuthServiceImpl.java
> +  @Transactional(noRollbackFor = InvalidPasswordException.class)
you can remove noRollbackFor after addressing the comments at inCrementFailedLoginAttempt

2024-10-25 05:43 UTC, nnagwani-traitfit commented
@abhishekTraitFit The PR looks good to me. Please address comments from @BhargavaNarendra97 and CodeRabbit. I think they have covered all the points. One point which they might have missed is the impact changing the pincode key could have on FE. I am not sure if they are using it at all, but if they are this must be communicated to them so that they can do the relevant change on their side.

2024-10-28 05:08 UTC, BhargavaNarendra97 approved these changes

2024-10-28 05:13 UTC, merged